FROM pavlovmedia/pavlov-felix-container                                                                                
MAINTAINER Pavlov Media <dev@pavlovmedia.com>                                                                       
                                                                                                                          
ADD target/lib/ /opt/felix/current/bundle/